name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install Go
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      
      # Step 2: Checkout the repository
      - uses: actions/checkout@v2

      # Step 3: Generate Golang protobuf and gRPC code
      - name: "Generate for Golang"
        run: |
          sudo apt-get install -y protobuf-compiler golang-goprotobuf-dev
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          protoc --go_out=./golang --go_opt=paths=source_relative --go-grpc_out=./golang --go-grpc_opt=paths=source_relative ./**/*.proto
          cd golang
          go mod init github.com/TrapLord92/microservices-proto
          go mod tidy

      # Step 4: Commit and push the generated files back to the repository
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub Token for authentication
        run: |
          git config --global user.email "traplord345@gmail.com"
          git config --global user.name "TrapLord92"
          git add .
          git commit -am "proto update"
          git push origin main
